=== SSwiatlak/IT_SYSTEM_FOR_CAR_WORKSHOPS/XMLProcessingApp/XML_files/MODA4_XMLSchema.xsd
<?xml version="1.0" encoding="windows-1252"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.moda4.com" elementFormDefault="qualified"
            xmlns:xdb="http://xmlns.oracle.com/xdb" targetNamespace="http://www.moda4.com">
  <xsd:element name="ZAMOWIENIA">
    <xsd:annotation>
      <xsd:documentation>A sample element</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="ZAMOWIENIE" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="POZYCJA_ZAMOWIENIA" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence minOccurs="1" maxOccurs="1">
                    <xsd:element name="POJAZD" minOccurs="0" maxOccurs="1">
                      <xsd:complexType>
                        <xsd:attribute name="MARKA" use="required" type="xsd:string"/>
                        <xsd:attribute name="MODEL" use="required" type="xsd:string"/>
                        <xsd:attribute name="ROCZNIK" use="required" type="xsd:gYear"/>
                        <xsd:attribute name="NR_VIN" use="optional" type="VIN"/>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="LP" use="required" type="xsd:integer"/>
                  <xsd:attribute name="NR_OEM" type="OEM" use="required"/>
                  <xsd:attribute name="ILOSC" use="required" type="xsd:decimal"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="NR_ZAMOWIENIA" use="required" type="xsd:string"/>
            <xsd:attribute name="DATA_ZAMOWIENIA" use="required" type="xsd:date"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="OEM">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="30"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="VIN">
    <xsd:restriction base="xsd:string">
      <xsd:length value="17"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== SSwiatlak/IT_SYSTEM_FOR_CAR_WORKSHOPS/XML/MODA4_XML_p1.xml
<?xml version="1.0"?>
<ZAMOWIENIA xmlns="http://www.moda4.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.moda4.com file:/C:/JDeveloper/mywork/projekt1/UML/MODA4_XMLSchema.xsd">
  <ZAMOWIENIE NR_ZAMOWIENIA="25/01/0001" DATA_ZAMOWIENIA="2025-01-08">
    <POZYCJA_ZAMOWIENIA LP="1" NR_OEM="1J0407151C" ILOSC="1">
      <POJAZD MARKA="Toyota" MODEL="Corolla" ROCZNIK="2018" NR_VIN="JTNBK3JF1J3145678"/>
    </POZYCJA_ZAMOWIENIA>
    <POZYCJA_ZAMOWIENIA LP="2" NR_OEM="1J0407152C" ILOSC="1">
      <POJAZD MARKA="Toyota" MODEL="Corolla" ROCZNIK="2018" NR_VIN="JTNBK3JF1J3145678"/>
    </POZYCJA_ZAMOWIENIA>
    <POZYCJA_ZAMOWIENIA LP="3" NR_OEM="1J0501529G" ILOSC="1"/>
    <POZYCJA_ZAMOWIENIA LP="4" NR_OEM="1J0501530G" ILOSC="2">
      <POJAZD MARKA="Ford" MODEL="Focus" ROCZNIK="2013" NR_VIN="WF0SXXGCBJY345678"/>
    </POZYCJA_ZAMOWIENIA>
  </ZAMOWIENIE>
  <ZAMOWIENIE NR_ZAMOWIENIA="25/01/0002" DATA_ZAMOWIENIA="2025-01-08">
    <POZYCJA_ZAMOWIENIA LP="1" NR_OEM="1J0129620" ILOSC="2">
      <POJAZD MARKA="Ford" MODEL="Focus" ROCZNIK="2013" NR_VIN="WF0SXXGCBJY345678"/>
    </POZYCJA_ZAMOWIENIA>
    <POZYCJA_ZAMOWIENIA LP="2" NR_OEM="04E115561H" ILOSC="1">
      <POJAZD MARKA="Audi" MODEL="A4" ROCZNIK="2020" NR_VIN="WAUZL98T5FA123456"/>
    </POZYCJA_ZAMOWIENIA>
    <POZYCJA_ZAMOWIENIA LP="3" NR_OEM="1J0819644A" ILOSC="1"/>
    <POZYCJA_ZAMOWIENIA LP="4" NR_OEM="1J0698451F" ILOSC="1">
      <POJAZD MARKA="Audi" MODEL="A4" ROCZNIK="2020" NR_VIN="WAUZL98T5FA123456"/>
    </POZYCJA_ZAMOWIENIA>
    <POZYCJA_ZAMOWIENIA LP="5" NR_OEM="038103483E" ILOSC="1">
      <POJAZD MARKA="Renault" MODEL="Clio" ROCZNIK="2022" NR_VIN="VF1BZD20023754897"/>
    </POZYCJA_ZAMOWIENIA>
  </ZAMOWIENIE>
  <ZAMOWIENIE NR_ZAMOWIENIA="25/01/0003" DATA_ZAMOWIENIA="2025-01-09">
    <POZYCJA_ZAMOWIENIA LP="1" NR_OEM="1J0919051D" ILOSC="1">
      <POJAZD MARKA="Peugeot" MODEL="308" ROCZNIK="2018" NR_VIN="1FWCZ51A3XH123456"/>
    </POZYCJA_ZAMOWIENIA>
    <POZYCJA_ZAMOWIENIA LP="2" NR_OEM="038103383M" ILOSC="1"/>
    <POZYCJA_ZAMOWIENIA LP="3" NR_OEM="G052167M4" ILOSC="45.5"/>
    <POZYCJA_ZAMOWIENIA LP="4" NR_OEM="G013A8J1G" ILOSC="50"/>
    <POZYCJA_ZAMOWIENIA LP="5" NR_OEM="1J0853855" ILOSC="1"/>
    <POZYCJA_ZAMOWIENIA LP="6" NR_OEM="8N0601025A" ILOSC="3"/>
  </ZAMOWIENIE>
  <ZAMOWIENIE NR_ZAMOWIENIA="25/01/0004" DATA_ZAMOWIENIA="2025-01-10">
    <POZYCJA_ZAMOWIENIA LP="1" NR_OEM="8N0601025A" ILOSC="3"/>
    <POZYCJA_ZAMOWIENIA LP="2" NR_OEM="G052167M4" ILOSC="20.5"/>
    <POZYCJA_ZAMOWIENIA LP="3" NR_OEM="G013A8J1G" ILOSC="30"/>
    <POZYCJA_ZAMOWIENIA LP="4" NR_OEM="1J0129620" ILOSC="1">
      <POJAZD MARKA="Peugeot" MODEL="308" ROCZNIK="2018" NR_VIN="1FWCZ51A3XH123456"/>
    </POZYCJA_ZAMOWIENIA>
    <POZYCJA_ZAMOWIENIA LP="5" NR_OEM="04E115561H" ILOSC="1">
      <POJAZD MARKA="Peugeot" MODEL="308" ROCZNIK="2018" NR_VIN="1FWCZ51A3XH123456"/>
    </POZYCJA_ZAMOWIENIA>
  </ZAMOWIENIE>
</ZAMOWIENIA>
